server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/test
    username: test
    password: 123456a?
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    changeLog: "classpath:/db/changelog/db.changelog-master.yaml"
#  h2:
#    console:
#      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"